STM32F446: fix startup and linker code
d-ronin/dRonin pull request #1356
Opened 2016-09-14 21:38 UTC by mluessi

Fixes and cleans up linker scripts for BrainRE1 and adds global linker scripts for STM32F446, also adds additional vectors to the startup code.

Fixes #1320

2016-09-14 22:13 UTC, mluessi commented
Bench tested with BrainRE1, seems to work.

2016-09-14 22:29 UTC, tracernz commented on flight/PiOS/STM32F4xx/library_chibios.mk
> +endif
Might be good to have an else with an explicit error rather than passing a blank linker script and getting something more cryptic.

2016-09-14 22:31 UTC, tracernz commented on flight/targets/bl/f4/Makefile
> +                        $(PIOS_DEVLIB)/link_STM32F446xx_sections.ld
As above, explicit error is nice.

2016-09-14 22:32 UTC, tracernz commented on flight/targets/bu/f4/Makefile
> +                        $(PIOS_DEVLIB)/link_STM32F446xx_sections.ld
Same again.

2016-09-14 22:34 UTC, tracernz requested changes

2016-09-14 22:35 UTC, tracernz commented
This review thing is quite nice. :+1:

2016-09-15 13:10 UTC, mluessi commented
@tracernz added explicit errors, good call.

2016-09-15 16:59 UTC, mluessi commented on flight/PiOS/STM32F4xx/library_chibios.mk
> +endif
done

2016-09-15 16:59 UTC, mluessi commented on flight/targets/bl/f4/Makefile
> +                        $(PIOS_DEVLIB)/link_STM32F446xx_sections.ld
done

2016-09-15 16:59 UTC, mluessi commented on flight/targets/bu/f4/Makefile
> +                        $(PIOS_DEVLIB)/link_STM32F446xx_sections.ld
done

2016-09-15 22:06 UTC, tracernz commented on flight/targets/bl/f4/Makefile
> +                        $(PIOS_DEVLIB)/link_STM32F446xx_sections.ld
Thanks

2016-09-15 22:07 UTC, tracernz approved these changes

2016-09-15 22:58 UTC, merged