battery: make estimated flight time nicer
d-ronin/dRonin pull request #1381
Opened 2016-09-23 06:33 UTC by mlyle

Use a second order filter, with longer rolloff, to come up with
remaining flight time estimates.  It will be optimistic for the first
20-30 seconds of a flight, but should be a pretty good estimate after
that.

2016-09-24 11:01 UTC, tracernz commented on flight/Modules/Battery/battery.c
> +			time_lpf = time_lpf * alpha + (1 - alpha) * flightBatteryData.AvgCurrent;
Not sure this is a particularly good variable name. `filtered_current` or something similar might be better?

2016-09-24 11:01 UTC, tracernz requested changes

2016-09-24 18:34 UTC, mlyle commented on flight/Modules/Battery/battery.c
> +			time_lpf = time_lpf * alpha + (1 - alpha) * flightBatteryData.AvgCurrent;
Done :)

2016-09-24 21:55 UTC, dustin commented
This works really well in my little testing today. Punch hard and then
float around in trees and it gave me a useful indicator as to when to come
home.

On Sat, Sep 24, 2016, 11:34 Michael Lyle <notifications@github.com> wrote:

> *@mlyle* commented on this pull request.
> ------------------------------
>
> In flight/Modules/Battery/battery.c
> <https://github.com/d-ronin/dRonin/pull/1381>:
>
> > @@ -227,8 +229,16 @@ static void batteryTask(void * parameters)
>  			flightBatteryData.AvgCurrent = alpha * flightBatteryData.AvgCurrent + (1 - alpha) * flightBatteryData.Current; //in Amps
>
>  			energyRemaining = batterySettings.Capacity - flightBatteryData.ConsumedEnergy; // in mAh
> -			if (flightBatteryData.AvgCurrent > 0)
> -				flightBatteryData.EstimatedFlightTime = (energyRemaining / (flightBatteryData.AvgCurrent * 1000.0f)) * 3600.0f; //in Sec
> +
> +			// And for time estimation, smooth things much more.
> +			// Second order since it incorporates the above
> +			// smoothing, 12s time constant for this layer.
> +			alpha = 1.0f - dT / (dT + 12.0f);
> +
> +			time_lpf = time_lpf * alpha + (1 - alpha) * flightBatteryData.AvgCurrent;
>
> Done :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/d-ronin/dRonin/pull/1381>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAG8_447lEEuIcCAd9nj7shWLt22CScks5qtW0sgaJpZM4KEpyX>
> .
>

2016-09-24 22:20 UTC, tracernz approved these changes

2016-09-25 13:53 UTC, mluessi commented on flight/Modules/Battery/battery.c
> +			// XXX Arguably this should be to 10% capacity or 15%
Yeah, we should make this configurable and default to 20%

2016-09-25 13:54 UTC, merged

2016-09-25 17:44 UTC, tracernz commented on flight/Modules/Battery/battery.c
> +			// XXX Arguably this should be to 10% capacity or 15%
Yah, the "rule" has always been 80% discharge.

2016-09-25 18:08 UTC, mlyle commented on flight/Modules/Battery/battery.c
> +			// XXX Arguably this should be to 10% capacity or 15%
Question is, should the time read 0 at 80% discharge?  Who does the 80%?  Probably us, but not sure.