gcs: esc calibration: send no pulses for 1.25s first
d-ronin/dRonin pull request #1410
Opened 2016-10-07 04:49 UTC by mlyle

Fixes #1170.

If the user doesn't listen and detach the battery and props, this gives
the ESC a chance to disarm by having no pulses.  No guarantees, etc...
Just slightly safer.

2016-10-13 06:07 UTC, tracernz requested changes

2016-10-13 06:07 UTC, tracernz commented on ground/gcs/src/plugins/config/configoutputwidget.cpp
> +    actuatorCommand->setData(actuatorCommandFields);
Don't you want to do this before loop.exec() so the output is disabled during that 1.25 s?

2016-10-13 06:37 UTC, mlyle commented on ground/gcs/src/plugins/config/configoutputwidget.cpp
> +    actuatorCommand->setData(actuatorCommandFields);
LOL that might help huh :)

2016-10-16 01:04 UTC, tracernz approved these changes

2016-10-16 01:05 UTC, tracernz commented
Looks good now, I'm confident it will work, but have you tested at all? :stuck_out_tongue:

2016-10-16 01:09 UTC, mlyle commented
i have not yet, no :(

2016-11-02 01:01 UTC, tracernz commented
I really need to double-check this and merge. :D

2016-11-07 08:19 UTC, tracernz commented
Works great. :+1:

2016-11-07 08:20 UTC, merged