Flight: BrainRE1 - Move to new buzzer infrastructure.
d-ronin/dRonin pull request #1422
Opened 2016-10-11 23:31 UTC by jihlein

Moves BrainRE1 buzzer control to new annunciator infrastructure.

Tested failsafe after initial arm, buzzed out "R" in morse as expected.

Changed the buzzer severity level, and it buzzed out "T" when disarmed and "I" when armed, again as expected.

2016-10-11 23:45 UTC, mlyle commented on flight/Modules/System/systemmod.c
> +#if defined(PIOS_INCLUDE_RE1_FPGA)
So hshred and I were talking about this before-- and I was wondering if you'd be willing to do this slightly differently.

We had the idea of maybe adding a callback to the pios_annunciator config that is used to change the value.  If it's not-NULL, the callback is called instead of setting a GPIO.  Then re1 could just provide a function that enables / disables the buzzer.

2016-10-11 23:46 UTC, mlyle requested changes
I like the UI and hook changes.  If you don't want to do the factoring into annunciator-- no biggie, I can do it in a few days and tack it onto this PR.

2016-10-12 00:11 UTC, jihlein commented
Hate to make more work for you, but I'm not sure how to implement what you are asking........

2016-10-12 02:56 UTC, mlyle commented
I pushed a change-- does this code work and look reasonable?  thx

2016-10-12 03:20 UTC, mlyle approved these changes

2016-10-12 12:26 UTC, jihlein commented on flight/targets/brainre1/board-info/board_hw_defs.c
> +#if defined(PIOS_INCLUDE_RE1_FPGA)
Since this is the BrainRE1 target, and the FPGA is an integral part of it, are lines 75 and 79 necessary?

2016-10-12 12:34 UTC, jihlein commented
Looks fine, one question above, see above comment.  Will test this evening.

2016-10-12 13:25 UTC, mluessi commented on flight/Modules/System/systemmod.c
> +#if defined(PIOS_INCLUDE_RE1_FPGA)
Shouldn't be needed now that the handler is used.

2016-10-12 13:26 UTC, mluessi commented on flight/targets/brainre1/board-info/board_hw_defs.c
> +#if defined(PIOS_INCLUDE_RE1_FPGA)
True, but I think it's used elsewhere in the same file, so we can also leave it there.

2016-10-12 13:27 UTC, mluessi commented
Thanks @jihlein and @mlyle. Other than the comment about the header in systemmod, it looks good to me.

2016-10-12 14:24 UTC, mlyle commented on flight/targets/brainre1/board-info/board_hw_defs.c
> +#if defined(PIOS_INCLUDE_RE1_FPGA)
It's necessary because the fpga support isn't linked into the bootupdater, so it gets a link error.

2016-10-12 15:07 UTC, mluessi commented on flight/targets/brainre1/board-info/board_hw_defs.c
> +#if defined(PIOS_INCLUDE_RE1_FPGA)
It is linked in the bootloader. Without it, there wouldn't be any LEDs on RE1 when the BL is active ;)

2016-10-12 17:54 UTC, mlyle commented on flight/targets/brainre1/board-info/board_hw_defs.c
> +#if defined(PIOS_INCLUDE_RE1_FPGA)
I said bootupdater, not bootloader.  If you remove the ifdef it blows up linking in the bootupdater.

2016-10-12 21:13 UTC, jihlein commented
Tested as above in first post.  Works correctly with the refactoring changes.

2016-10-13 05:13 UTC, mlyle commented
@tracernz / @hshred -- willing to merge?

2016-10-13 06:05 UTC, tracernz approved these changes
LGTM. @mluessi should do this one I think.

2016-10-13 11:43 UTC, mluessi commented
Thanks!

2016-10-13 11:43 UTC, merged