PIOS_DAC: Implement DAC driver
d-ronin/dRonin pull request #1515
Opened 2017-01-14 08:10 UTC by mlyle

This is WIP because it needs actual end-user useful functionality to merge.

May want to crank sample rate up too, because stair steps are fairly bad without an anti-aliasing filter.

2017-01-25 02:00 UTC, mlyle commented
Need a decent way to turn this on and off, and I think the pios_dac priority system needs a little help.

With #1525 plus this, I get:

![image](https://cloud.githubusercontent.com/assets/90903/22275073/f5af2e3a-e25e-11e6-8122-f8224e22d3ba.png)

2017-01-25 08:18 UTC, mlyle commented
With #1525, this works well ---- though configuration is necessary.  An annunciator target would be really nice.

An example from seppuku is at http://jar.lyle.org/~mlyle/data.wav

A crude demodulator is at: https://gist.github.com/mlyle/4e0db1cab991cdceb364dc2859c3099e

Which yields output like:

```
595 ___m8}____=____]m_Y____c_6_'__h_)__9_G_a_~n_____o________NN
687 $TA_______
778 $TA_______
944 $TG_______________
1035 $TA____B_A
1127 $TA____B_A
1228 $TS______NN
```

2017-01-25 08:20 UTC, mlyle commented
@peabody124 can you easily feed that data.wav to your tools to see whether we're interoperable?

2017-01-26 22:57 UTC, mlyle commented
![envelope](https://cloud.githubusercontent.com/assets/90903/22353912/a5c6124c-e3d7-11e6-9919-8daeae22ad1d.png)

http://jar.lyle.org/~mlyle/beepy.wav

I've tested both modes and selecting them from within the uavo browser.  works; I think this is ready for review.

2017-01-27 16:51 UTC, peabody124 commented
@mlyle I will try and check Sunday. On call today. Ping me on IRC then too if you don't hear anything

2017-01-28 00:42 UTC, mlyle commented
@peabody124 Thanks, much appreciated :D

2017-01-30 00:57 UTC, mlyle commented
Good news: it works, even before the minor magnitude adjustment above:

http://streamable.com/i3rh4

Bad news: I shorted my VTX while playing with the disassembled quad and it caught fire.  Woops.  Need to rewire stuff now.

2017-02-01 21:11 UTC, tracernz requested changes
Looks pretty good. :+1:

2017-02-01 21:11 UTC, tracernz commented on flight/PiOS/STM32F4xx/inc/pios_dac.h
> +typedef struct dac_dev_s *dac_dev_t;
Prefix with `pios_`?

2017-02-01 21:11 UTC, tracernz commented on flight/PiOS/inc/pios_annuncdac.h
> +typedef struct annuncdac_dev_s *annuncdac_dev_t;
`pios_`

2017-02-01 21:11 UTC, tracernz commented on flight/PiOS/inc/pios_fskdac.h
> +typedef struct fskdac_dev_s *fskdac_dev_t;
`pios_`

2017-02-01 23:36 UTC, mlyle commented on flight/PiOS/STM32F4xx/inc/pios_dac.h
> +typedef struct dac_dev_s *dac_dev_t;
Last several drivers we merged like ws2811, max7456, lis3mdl we had decided not to do that and to move towards changing the convention.   Want to revisit?

2017-02-02 09:29 UTC, tracernz commented on flight/PiOS/STM32F4xx/inc/pios_dac.h
> +typedef struct dac_dev_s *dac_dev_t;
Ah yes. I still think this kind of artificial namespacing is good but the horse has already bolted.

2017-02-02 09:29 UTC, merged