actuators: some small simplifications and code cleanups
d-ronin/dRonin pull request #1594
Opened 2017-02-25 22:24 UTC by mlyle

- Existing code for LEDs and buzzer is not useful.  Redirecting output
from existing annunciator subsystem up at the mixer level could
eventually be worthwhile and cleaner.
- Reclaim horizontal space from that pulldown on the output pane / make
things less busy.
- Clarify some comments.

2017-02-28 22:46 UTC, tracernz requested changes

2017-02-28 22:46 UTC, tracernz commented on flight/Modules/Actuator/actuator.c
>  		bool success = true;
Should remove this too since it no longer does anything. Can probably also remove ActuatorCommand.NumFailedUpdates?

2017-02-28 23:45 UTC, mlyle commented on flight/Modules/Actuator/actuator.c
>  		bool success = true;
Good eye.

2017-03-01 00:55 UTC, tracernz approved these changes

2017-03-10 23:04 UTC, merged