sim: simsensors: support external simulator
d-ronin/dRonin pull request #1885
Opened 2017-07-12 22:17 UTC by mlyle

2017-07-13 22:59 UTC, mlyle commented
jenkins, build artifacts please

2017-07-13 23:08 UTC, mlyle commented
jenkins, test this please

2017-07-14 07:56 UTC, tracernz commented on flight/Modules/Sensors/simulated/simsensors.c
> +#if !(defined(_WIN32) || defined(WIN32) || defined(__MINGW32__))
I see this combo a lot. We should probably have a macro somewhere so it's maintainable (and actually, our Makefiles already determine this right?).

2017-07-14 16:24 UTC, mlyle commented on flight/Modules/Sensors/simulated/simsensors.c
> +#if !(defined(_WIN32) || defined(WIN32) || defined(__MINGW32__))
Yes-- probably should have a different sub-architecture though (like we have common/stm32/stm32f4xx .. could have common/posix/posixwin/ or whatever, with associated defines etc like firmware-arches does

2017-07-27 07:13 UTC, tracernz commented on flight/Modules/Sensors/simulated/simsensors.c
> +			PIOS_Thread_Sleep_Until(&tm, 5);
`PIOS_Thread_Sleep_Until(&tm, 1000 / sens_rate)`?

2017-07-27 07:16 UTC, tracernz commented on flight/Modules/Sensors/simulated/simsensors.c
> +extern bool use_yasim;
Would be nice to pass this through nicely somehow. PIOS_Sensors seems like the right place.. but not specific to sim currently :/.

2017-07-27 07:16 UTC, tracernz commented on flight/Modules/Sensors/simulated/simsensors.c
> +	    float resv[8];
Reserved?

2017-07-27 07:18 UTC, tracernz commented on flight/Modules/Sensors/simulated/simsensors.c
> +	if(baro_offset == 0) {
space

2017-07-27 07:18 UTC, tracernz commented on flight/Modules/Sensors/simulated/simsensors.c
> +	if(PIOS_DELAY_DiffuS(last_mag_time) / 1.0e6 > MAG_PERIOD) {
space

2017-07-27 07:18 UTC, tracernz commented on flight/Modules/Sensors/simulated/simsensors.c
> +	if(PIOS_DELAY_DiffuS(last_baro_time) / 1.0e6 > BARO_PERIOD) {
space

2017-07-27 07:18 UTC, tracernz commented on flight/Modules/Sensors/simulated/simsensors.c
> +					"/home/mlyle/drhil/pa22-160-yasim.xml",
Hardcoded path

2017-07-27 07:19 UTC, tracernz commented on flight/Modules/Sensors/simulated/simsensors.c
> +	    float resv[4];
The abbreviation only obfuscates IMO, and it's not used so no win in brevity.

2017-07-27 07:22 UTC, tracernz requested changes
Hardcoded path.

2017-07-27 14:50 UTC, mlyle commented
Woops :P

2017-07-27 16:56 UTC, mlyle commented on flight/Modules/Sensors/simulated/simsensors.c
> +	    float resv[4];
It's the "standard" way to write reserved.  That or someprefix_reserved.

2017-07-27 16:57 UTC, mlyle commented on flight/Modules/Sensors/simulated/simsensors.c
> +extern bool use_yasim;
Yah.  It's like posix needs some kind of configuration registry for things like this--- ultimately moving away from the command line to a config file and adding a small API would help for this.

2017-08-13 05:01 UTC, tracernz approved these changes

2017-08-13 06:07 UTC, mlyle commented
jenkins, test this please

2017-08-18 03:09 UTC, merged